apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: sbom-gt-no-build-insert
spec:
  taskRunSpecs:
    - pipelineTaskName: build-container
      stepSpecs:
        # Expected: replace with build stepSpec (req 11.5Gi / limit 12Gi)
        - name: sbom-syft-generate
          computeResources:
            requests:
              memory: 11.5Gi
            limits:
              memory: 12Gi
  pipelineSpec:
    tasks:
      - name: build-container
        taskRef:
          resolver: bundles
          params:
            - name: kind
              value: task
            - name: name
              value: buildah
            - name: bundle
              value: quay.io/konflux-ci/tekton-catalog/task-buildah:0.2
