apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: sbom-mi-gt-build-gi
spec:
  taskRunSpecs:
    - pipelineTaskName: build-container
      stepSpecs:
        # Expected: bump build to 8000Mi, remove sbom stepSpec
        # (8000Mi = 8388608000 > 4Gi = 4294967296)
        - name: build
          computeResources:
            requests:
              memory: 4Gi
            limits:
              memory: 4Gi
        - name: sbom-syft-generate
          computeResources:
            requests:
              memory: 8000Mi
            limits:
              memory: 8000Mi
  pipelineSpec:
    tasks:
      - name: build-container
        taskRef:
          resolver: bundles
          params:
            - name: kind
              value: task
            - name: name
              value: buildah
            - name: bundle
              value: quay.io/konflux-ci/tekton-catalog/task-buildah:0.2
