apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: plr-referencing-pipeline-bump
spec:
  pipelineRef:
    name: test-pipeline
  taskRunSpecs:
    - pipelineTaskName: build-container
      stepSpecs:
        # Expected: bump build to 10Gi, remove sbom stepSpec
        - name: build
          computeResources:
            requests:
              memory: 4Gi
            limits:
              memory: 4Gi
        - name: sbom-syft-generate
          computeResources:
            requests:
              memory: 10Gi
            limits:
              memory: 10Gi
