---
apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: build-definitions-pull-request
  annotations:
    pipelinesascode.tekton.dev/on-cel-expression: (event == "pull_request" && target_branch == "main" && ( !has(body.pull_request) || !body.pull_request.draft) ) || (event == "push" && target_branch.startsWith("gh-readonly-queue/main/"))
    pipelinesascode.tekton.dev/task: "[task/git-clone/0.1/git-clone.yaml, .tekton/tasks/buildah.yaml, .tekton/tasks/yaml-lint.yaml, task/sast-snyk-check/0.1/sast-snyk-check.yaml]"
    pipelinesascode.tekton.dev/task-2: "yaml-lint"
    pipelinesascode.tekton.dev/max-keep-runs: "5"
spec:
  params:
    - name: repo_url
      value: "{{ repo_url }}"
    - name: revision
      value: "{{ revision }}"
    - name: e2e_test_namespace
      value: build-templates-e2e
  pipelineSpec:
    params:
      - name: repo_url
      - name: revision
      - name: e2e_test_namespace
    workspaces:
      - name: workspace
    tasks:
      - name: fetch-repository
        taskRef:
          name: git-clone
        workspaces:
          - name: output
            workspace: workspace
        params:
          - name: url
            value: $(params.repo_url)
          - name: revision
            value: $(params.revision)
          - name: depth
            value: "0"
      - name: yaml-lint-check
        runAfter:
          - fetch-repository
        taskRef:
          name: yaml-lint
        workspaces:
          - name: shared-workspace
            workspace: workspace
        params:
        - name: args
          value: [".", "-c", "/workspace/shared-workspace/source/.yamllint"]
      - name: sast-snyk-check
        params:
          - name: SNYK_SECRET
            value: snyk-shared-secret
        runAfter:
          - fetch-repository
        taskRef:
          name: sast-snyk-check
        workspaces:
          - name: workspace
            workspace: workspace
      - name: build-container
        runAfter:
          - yaml-lint-check
        params:
          - name: IMAGE
            value: quay.io/acmiel-test/pull-request-builds:build-definitions-utils-{{revision}}
          - name: CONTEXT
            value: appstudio-utils
        taskRef:
          name: buildah
        workspaces:
          - name: source
            workspace: workspace
      - name: build-bundles
        params:
          - name: revision
            value: "{{ revision }}"
          - name: e2e_test_namespace
            value: $(params.e2e_test_namespace)
        runAfter:
          - build-container
        workspaces:
          - name: source
            workspace: workspace
        taskSpec:
          params:
            - name: revision
              type: string
            - name: e2e_test_namespace
              type: string
          steps:
            - name: build-bundles
              image: quay.io/acmiel-test/pull-request-builds:build-definitions-utils-{{revision}}
              # per https://kubernetes.io/docs/concepts/containers/images/#imagepullpolicy-defaulting
              # the cluster will set imagePullPolicy to IfNotPresent
              workingDir: $(workspaces.source.path)/source
              script: |
                #!/usr/bin/env bash
                QUAY_NAMESPACE=acmiel-test/tekton-catalog \
                TEST_REPO_NAME=pull-request-builds \
                BUILD_TAG=$(params.revision) \
                SKIP_BUILD=1 \
                SKIP_INSTALL=1 \
                ENABLE_SOURCE_BUILD=1 \
                hack/build-and-push.sh
          workspaces:
            - name: source
      - name: check-task-pipeline-repo-existence
        runAfter:
          - build-container
        taskSpec:
          steps:
            - name: fail-when-repo-is-missed
              image: quay.io/acmiel-test/pull-request-builds:build-definitions-utils-{{revision}}
              # per https://kubernetes.io/docs/concepts/containers/images/#imagepullpolicy-defaulting
              # the cluster will set imagePullPolicy to IfNotPresent
              workingDir: $(workspaces.source.path)/source
              script: |
                #!/usr/bin/env bash
                .tekton/scripts/check-task-pipeline-bundle-repos.sh
          workspaces:
            - name: source
        workspaces:
          - name: source
            workspace: workspace
      - name: ec-task-checks
        runAfter:
          - fetch-repository
        taskRef:
          name: ec-checks
        workspaces:
          - name: source
            workspace: workspace
      - name: check-task-migration-md
        runAfter:
          - fetch-repository
        taskSpec:
          steps:
            - name: check-task-migration-md
              image: registry.redhat.io/openshift4/ose-tools-rhel8:v4.12@sha256:9deda623e4768ecbaa6f1c6204077d9a151d55f9569bfe414e793fcb36cc391e
              # per https://kubernetes.io/docs/concepts/containers/images/#imagepullpolicy-defaulting
              # the cluster will set imagePullPolicy to IfNotPresent
              workingDir: $(workspaces.source.path)/source
              script: |
                #!/usr/bin/env bash
                EXIT=0
                for TASK_DIR in $(ls task); do
                  # Do not check on initial version of task
                  for VERSION in $(ls -d task/$TASK_DIR/*/ | sort --version-sort | tail -n+2); do
                    MIGRATION_FILE=${VERSION}MIGRATION.md
                    if [ ! -f $MIGRATION_FILE ]; then
                       echo "Missing file $MIGRATION_FILE"
                       EXIT=1
                    fi
                  done
                done
                exit $EXIT
          workspaces:
            - name: source
        workspaces:
          - name: source
            workspace: workspace
  timeouts:
    pipeline: "2h"
  workspaces:
    - name: workspace
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
